### ISSUE TITLE
Need to hire for similar project

### ISSUE THREAD

**Issue by imanjj** [conatsera/k4a_cuda#1]
Hi!
Thanks for this very helpful code. I need to stream colored K4A point cloud in Unity. I'm not a unity developer myself. I'm hiring someone to implement this as well as other features. Can you please tell me the steps required for colored point cloud streaming in Unity?

Best,
Iman

**Comment by conatsera** [comment]
First, a color calibrated xy_table would need to be generated to interpolate depth onto the color pixels.  Next, one of the transformation helper functions provided by the SDK, k4a_transformation_depth_image_to_color_camera or k4a_transformation_color_image_to_depth_camera, would be used on the depth image to create a new depth image that matches the layout of the color image. This transformed depth image would then be processed using the xy_table to create a point cloud within the bounds of the smaller capture area. 
The array would be trimmed of extraneous data and conditionally reduced. Reduction is necessary if Unity's ParticleSystem is used as the particle budget is fairly low. A shader based render of the data would fair much better.

In WFOV the point cloud is a subset of the total depth input, while in NFOV it is a subset of the color image
https://docs.microsoft.com/en-us/azure/Kinect-dk/hardware-specification#camera-field-of-view
An example of using the SDK-based transformation can be found here:
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/tree/develop/examples/transformation

The intent of this project is replace the linear transformation methods in the SDK with parallelized CUDA kernels. I will have a CUDA implementation of the above completed within the next day or two.

**Comment by conatsera** [comment]
I've added color point cloud support in the latest commit
99efc434830679855f4a1ebec9a6f20c74dce2f7

There is still some optimization work to do, but it already performs better than the SDK point cloud functions.
If you need help with Unity side of things, please contact me: austin@amass.space

**Comment by imanjj** [comment]
Awesome, thanks much!
